# Generated by Django 3.2.4 on 2024-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('OK', 'Okay'), ('GD', 'Good'), ('GT', 'Great')], default='OK', max_length=2),
        ),
    ]
