# Generated by Django 3.2.4 on 2024-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.CharField(choices=[('OK', 'Okay'), ('GD', 'Good'), ('GT', 'Great')], default='OK', max_length=2),
        ),
    ]
