# Generated by Django 4.2 on 2024-07-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
        ('selected', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select', to='posts.post'),
        ),
    ]
